version: "3.3"

networks:
    default:
      external:
        name: frontendnet
services:
  postgres:
    image: postgres:16.1-alpine
    env_file: .env
    volumes:
      - /var/data/postgres/:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
